################################ datasource ############################
spring:
  datasource:
    url: jdbc:mysql://10.20.4.22:3306/elastic?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: yipeng_admin
    password: SIplo76Pi9HvZazG3I
    driverClassName: com.mysql.jdbc.Driver
#  jpa:
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: create